book/urls.py
from django.urls import path
from .views import (HomeView, AuthorsList, AuthorsDetail,
                    AuthorCreation, AuthorBooksEdit)

app_name = 'book'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('authors/', AuthorsList.as_view(), name='authors'),
    path('authors/<str:pk>', AuthorsDetail.as_view(), name='authors-detail'),
    path('authors/add/', AuthorCreation.as_view(), name='authors-add'),
    path('authors/<str:pk>/books/edit/', AuthorBooksEdit.as_view(), name='author-books-edit'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('book.urls', namespace='book'))
]

book/models.py
from django.db import models
from django.db.models import CharField

from django.urls import reverse


class Author(models.Model):
    name = models.CharField(max_length=32, null=False, blank=False)

    def get_absolute_url(self) -> str:
        return reverse(viewname='book:authors-detail', kwargs={'pk': self.pk})

    def __str__(self) -> CharField:
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=100, null=False, blank=False)
    author = models.ForeignKey(to='Author', on_delete=models.CASCADE,
                               null=False, blank=False, related_name='books')

    def __str__(self) -> CharField:
        return self.title

book/forms.py
from django.forms.models import inlineformset_factory

from .models import Author, Book

AuthorBooksFormset = inlineformset_factory(Author, Book, fields=('title',))

book/views.py
from typing import Any

from django.contrib import messages
from django.urls import reverse_lazy, reverse
from django.views.generic.detail import SingleObjectMixin
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.views.generic import (TemplateView, ListView,
                                  DetailView, CreateView, FormView)

from .models import Author

from .forms import AuthorBooksFormset


class HomeView(TemplateView):
    template_name = 'book/home.html'


class AuthorsList(ListView):
    model = Author


class AuthorsDetail(DetailView):
    queryset = Author.objects.prefetch_related('books').all()
    fields = ['name']


class AuthorCreation(CreateView):
    model = Author
    fields = ['name']
    success_url = reverse_lazy('book:authors')


class AuthorBooksEdit(SingleObjectMixin, FormView):
    model = Author
    template_name = 'book/author_books_edit.html'

    def get(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        self.object = self.get_object(queryset=Author.objects.prefetch_related('books').all())
        return super().get(request, *args, **kwargs)

    def post(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        self.object = self.get_object(queryset=Author.objects.prefetch_related('books').all())
        return super().post(request, *args, **kwargs)

    def get_form(self, form_class=None) -> Any:
        return AuthorBooksFormset(**self.get_form_kwargs(), instance=self.object)

    def form_valid(self, form) -> HttpResponseRedirect:
        form.save()
        messages.add_message(
            self.request,
            messages.SUCCESS,
            'Changes were saved !',
        )

        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self) -> str:
        return reverse(viewname='book:authors-detail', args=[self.object.pk])

book/templates/book/author_books_edit.html
{% extends 'book/base.html' %}

{% block title %}Editing books for {{ author.name }}{% endblock %}

{% block content %}
  <form action="" method="post" enctype="multipart/form-data">

    {% for hidden_field in form.hidden_fields %}
      {{ hidden_field.errors }}
      {{ hidden_field }}
    {% endfor %}

    {% csrf_token %}

    {{ form.management_form }}
    {{ form.non_form_errors }}

    <h3>Update Collection</h3>
    {% for book_form in form.forms %}
      <hr>
      <h5>
        {% if book_form.instance.id %}
          Book: {{ book_form.instance.title|title }}
        {% else %}
          {% if form.forms|length > 1 %}
            Add another book
          {% else %}
            Add a book
          {% endif %}
        {% endif %}
      </h5>
      {% for hidden_field in book_form.hidden_fields %}
        {{ hidden_field.errors }}
      {% endfor %}
      <table>
        {{ book_form.as_table }}
      </table>
    {% endfor %}
    <hr>
    <p>
      <button type="submit" value="Update collection" class="btn btn-primary w-100 mb-3">Update Collection</button>
      <a href="{{ author.get_absolute_url  }}" role="button" class="btn btn-secondary w-100">Cancel</a>
    </p>
  </form>

{% endblock content %}

book/templates/book/author_detail.html
{% extends 'book/base.html' %}

{% block title %}{{ author.name }}{% endblock %}

{% block content %}

    <h3>Authors Book Details</h3>
    <div class="d-flex d-flex-inline"><span class="pe-2">Authors name:</span> <h5>{{ author.name|title }}</h5></div>
    <hr>
        {% for book in author.books.all %}
        <div class="small">Book ID: {{ book.id }}</div>
        <div>Title: {{ book.title }}</div>
        <hr>
        {% endfor %}
    <p>
        <a href="{% url 'book:author-books-edit' author.id %}" role="button" class="btn btn-primary w-100 mb-2">Edit Authors Books</a>
        <a href="{% url 'book:authors' %}" role="button" class="btn btn-secondary w-100">Back to Authors</a>
    </p>


{% endblock content %}

book/templates/book/author_form.html
{% extends 'book/base.html' %}

{% block title %}New Author{% endblock %}

{% block content %}

      <form action="" method="post">
        {% for hidden_field in form.hidden_fields %}
          {{ hidden_field.errors }}
          {{ hidden_field }}
        {% endfor %}

        {% csrf_token %}

        {{ form.non_form_errors }}

        {% for field in form %}
          {{ field.errors }}
          {{ field.label_tag }} {{ field }}
        {% endfor %}

        <p class="pt-2">
            <button type="submit" class="btn btn-primary w-100 mb-2">Add Author</button>
            <a href="{% url 'book:home' %}" role="button" class="btn btn-secondary w-100">Back</a>
        </p>
      </form>

{% endblock content %}

book/templates/book/author_list.html
{% extends 'book/base.html' %}

{% block title %}Authors{% endblock %}

{% block content %}

<h1 class="h3">Authors</h1>

 {% if object_list %}

    <ul class="list-group">
      {% for object in object_list %}
        <li class="list-group-item">
          <a class="text-reset" href="{{ object.get_absolute_url }}">{{ object.name }}</a>
        </li>
      {% endfor %}
    </ul>

  {% else %}

    <p>There are no author to display.</p>

  {% endif %}

    <p class="pt-2">
      <a href="{% url 'book:home' %}" role="button" class="btn btn-secondary w-100">Back</a>
    </p>

{% endblock content %}

book/templates/book/base.html
<!doctype html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <title>{% block title %}Homepage{% endblock %}</title>
  </head>
  <body>
    <main>
      <div class="container-fluid">
        <div class="d-flex align-items-center py-5">
          <div class="col-12 col-md-6 col-lg-4 mx-auto">
            {% block content %}
            {% endblock content %}
          </div>
        </div>
      </div>
    </main>
  </body>
</html>

book/templates/book/home.html
{% extends 'book/base.html' %}

{% block title %}Homepage{% endblock %}

{% block content %}

    <h3>BookStore Collections</h3>
    <a href="{% url 'book:authors' %}" role="button" class="btn btn-primary w-100 mb-2">All Authors</a>
    <a href="{% url 'book:authors-add' %}" role="button" class="btn btn-secondary w-100">Add an Author</a>

{% endblock content %}